when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            # Disable expensive data collection for better performance
            collect_serializer_data: false
            only_exceptions: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
